export const LANGUAGES = [
  { code: 'en', native: 'English', speechLocale: 'en-US' },
  { code: 'as', native: 'অসমীয়া', speechLocale: 'as-IN' },
  { code: 'bn', native: 'বাংলা', speechLocale: 'bn-IN' },
  { code: 'brx', native: 'बड़ो', speechLocale: 'brx-IN' },
  { code: 'doi', native: 'डोगरी', speechLocale: 'doi-IN' },
  { code: 'gu', native: 'ગુજરાતી', speechLocale: 'gu-IN' },
  { code: 'hi', native: 'हिन्दी', speechLocale: 'hi-IN' },
  { code: 'kn', native: 'ಕನ್ನಡ', speechLocale: 'kn-IN' },
  { code: 'ks', native: 'کٲشُر', rtl: true, speechLocale: 'ks-IN' },
  { code: 'kok', native: 'कोंकणी', speechLocale: 'kok-IN' },
  { code: 'mai', native: 'मैथिली', speechLocale: 'mai-IN' },
  { code: 'ml', native: 'മലയാളം', speechLocale: 'ml-IN' },
  { code: 'mni', native: 'ꯃꯩꯇꯩꯂꯣꯟ', speechLocale: 'mni-IN' },
  { code: 'mr', native: 'मराठी', speechLocale: 'mr-IN' },
  { code: 'ne', native: 'नेपाली', speechLocale: 'ne-NP' },
  { code: 'or', native: 'ଓଡ଼ିଆ', speechLocale: 'or-IN' },
  { code: 'pa', native: 'ਪੰਜਾਬੀ', speechLocale: 'pa-IN' },
  { code: 'sa', native: 'संस्कृतम्', speechLocale: 'sa-IN' },
  { code: 'sat', native: 'ᱥᱟᱱᱛᱟᱲᱤ', speechLocale: 'sat-IN' },
  { code: 'sd', native: 'سنڌي', rtl: true, speechLocale: 'sd-IN' },
  { code: 'ta', native: 'தமிழ்', speechLocale: 'ta-IN' },
  { code: 'te', native: 'తెలుగు', speechLocale: 'te-IN' },
  { code: 'ur', native: 'اردو', rtl: true, speechLocale: 'ur-IN' },
] as { code: string; native: string; rtl?: boolean; speechLocale: string }[]